
service: sns-test

provider:
  name: aws
  runtime: nodejs6.10

functions:
  pong:
    handler: pong.handler
    events:
      - sns: test-topic
  ping:
    handler: ping.handler
    events:
      - http:
          path: ping
          method: get
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-sns

custom:
  serverless-offline-sns:
    port: 4002
    debug: true
  webpackIncludeModules: true
